import Head from 'next/head'
import Header from './header'

const Layout = ({children}) => {
    return (
        <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      {children}
          
        </>
    )
}

export default Layout